namespace DTA.Database.Migrations
{
    using DTA.Entities;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<DTA.Database.LibraryDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true; //Will become false after we have enough data and the model is tested.
        }

        protected override void Seed(DTA.Database.LibraryDbContext context)
        {
            //1============================ Authors
            Author a1 = new Author() { AuthorId = 1, FirstName = "J. J. R.", LastName = "Tolkien" };
            Author a2 = new Author() { AuthorId = 2, FirstName = "Isaac", LastName = "Asimov" };
            Author a3 = new Author() { AuthorId = 3, FirstName = "Paulo", LastName = "Coelho" };
            Author a4 = new Author() { AuthorId = 4, FirstName = "Alexandre", LastName = "Dumas" };
            Author a5 = new Author() { AuthorId = 5, FirstName = "George R. R.", LastName = "Martin" };
            Author a6 = new Author() { AuthorId = 6, FirstName = "Fyodor", LastName = "Dostoyevsky" };
            Author a7 = new Author() { AuthorId = 7, FirstName = "R. A.", LastName = "Salvatore" };
            Author a8 = new Author() { AuthorId = 8, FirstName = "Eiichiro", LastName = "Oda" };
            Author a9 = new Author() { AuthorId = 9, FirstName = "Hiro", LastName = "Mashima" };
            Author a10 = new Author() { AuthorId = 10, FirstName = "Osamu", LastName = "Tezuka" };
            Author a11 = new Author() { AuthorId = 11, FirstName = "James", LastName = "Clear" };
            Author a12 = new Author() { AuthorId = 12, FirstName = "Marcus", LastName = "Aurelius" };
            Author a13 = new Author() { AuthorId = 13, FirstName = "Sally", LastName = "Rooney" };
            Author a14 = new Author() { AuthorId = 14, FirstName = "John", LastName = "Elton" };
            Author a15 = new Author() { AuthorId = 15, FirstName = "Philip", LastName = "Pullman" };
            Author a16 = new Author() { AuthorId = 16, FirstName = "Philippe", LastName = "Besson" };
            Author a17 = new Author() { AuthorId = 17, FirstName = "Chigozie", LastName = "Obioma" };
            Author a18 = new Author() { AuthorId = 18, FirstName = "Adam", LastName = "Kay" };
            Author a19 = new Author() { AuthorId = 19, FirstName = "Andre", LastName = "Aciman" };
            Author a20 = new Author() { AuthorId = 20, FirstName = "Holly", LastName = "Webb" };
            Author a21 = new Author() { AuthorId = 21, FirstName = "Bill", LastName = "Bryson" };
            Author a22 = new Author() { AuthorId = 22, FirstName = "Terry", LastName = "Goodkind" };
            Author a23 = new Author() { AuthorId = 23, FirstName = "Andrzej", LastName = "Sapkowski" };
            Author a24 = new Author() { AuthorId = 24, FirstName = "Philip K.", LastName = "Dick" };
            Author a25 = new Author() { AuthorId = 25, FirstName = "Frank", LastName = "Herbert" };
            Author a26 = new Author() { AuthorId = 26, FirstName = "Yuval Noah", LastName = "Harari" };
            Author a27 = new Author() { AuthorId = 27, FirstName = "Stephen", LastName = "Hawking" };
            Author a28 = new Author() { AuthorId = 28, FirstName = "David", LastName = "Allen" };
            Author a29 = new Author() { AuthorId = 29, FirstName = "Ken", LastName = "Mogi" };
            Author a30 = new Author() { AuthorId = 30, FirstName = "Jordan B.", LastName = "Peterson" };
            Author a31 = new Author() { AuthorId = 31, FirstName = "John", LastName = "Cottingham" };
            Author a32 = new Author() { AuthorId = 32, FirstName = "Sun", LastName = "Tzu" };
            Author a33 = new Author() { AuthorId = 33, FirstName = "Eric", LastName = "Taylor" };
            Author a34 = new Author() { AuthorId = 34, FirstName = "Andrew", LastName = "Graham-Dixon" };
            Author a35 = new Author() { AuthorId = 35, FirstName = "Hayao", LastName = "Miyazaki" };
            context.Authors.AddOrUpdate(x => x.LastName, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35);
            context.SaveChanges();

            //2============================ Categories
            Category c1 = new Category() { CategoryId = 1, Title = "Fantasy" };
            Category c2 = new Category() { CategoryId = 2, Title = "Science Fiction" };
            Category c3 = new Category() { CategoryId = 3, Title = "Novel" };
            Category c4 = new Category() { CategoryId = 4, Title = "Manga" };
            Category c5 = new Category() { CategoryId = 5, Title = "Popular Science" };
            Category c6 = new Category() { CategoryId = 6, Title = "Personal Development" };
            Category c7 = new Category() { CategoryId = 7, Title = "Philosophy" };
            Category c8 = new Category() { CategoryId = 8, Title = "Music" };
            Category c9 = new Category() { CategoryId = 9, Title = "Art" };
            context.Categories.AddOrUpdate(x => x.Title, c1, c2, c3, c4, c5, c6, c7, c8, c9);
            context.SaveChanges();

            //3============================ Books
            Book b1 = new Book() { BookId = 1, Title = "Lord of the Rings", Category = c1, Author = a1, Price = 10, Language = "English", YearPublished = 2017, ISBN = 1847941834, Cover = "~/Covers/lordoftherings.jpg", Description = "Continuing the story begun in The Hobbit, all three parts of the epic masterpiece, The Lord of the Rings, in one paperback. Features the definitive edition of the text, fold-out flaps with the original two-colour maps, and a revised and expanded index." };
            Book b2 = new Book() { BookId = 2, Title = "The Silmarillion", Category = c1, Author = a1, Price = 7, Language = "English", YearPublished = 2013, ISBN = 0261102737, Cover = "~/Covers/silmarilion.jpg", Description = "Designed to take fans of The Hobbit and The Lord of the Rings deeper into the myths and legends of Middle-earth." };
            Book b3 = new Book() { BookId = 3, Title = "The Hobbit", Category = c1, Author = a1, Price = 5, Language = "English", YearPublished = 1991, ISBN = 0261102214, Cover = "~/Covers/hobbit.jpg", Description = "The Hobbit is a tale of high adventure, undertaken by a company of dwarves in search of dragon-guarded gold. Written by Professor Tolkien for his own children, The Hobbit met with instant critical acclaim when published." };
            Book b4 = new Book() { BookId = 4, Title = "The End of Eternity", Category = c2, Author = a2, Price = 4, Language = "English", YearPublished = 2011, ISBN = 0586024409, Cover = "~/Covers/endofeternity.jpg", Description = "The best time-travel story since H.G. Wells's The Time Machine, by the Grand Master of science fiction, the story of Andrew Harlan, Technician and Eternal." };
            Book b5 = new Book() { BookId = 5, Title = "The Alchemist", Category = c3, Author = a3, Price = 5.5M, Language = "English", YearPublished = 2014, ISBN = 0062315005, Cover = "~/Covers/alchemist.jpg", Description = "Santiago, a young shepherd living in the hills of Andalucia, feels that there is more to life than his humble home and his flock. One day he finds the courage to follow his dreams into distant lands, each step galvanised by the knowledge that he is following the right path: his own. The people he meets along the way, the things he sees and the wisdom he learns are life-changing." };
            Book b6 = new Book() { BookId = 6, Title = "One Piece, Vol. 1", Category = c4, Author = a8, Price = 9.5M, Language = "English", YearPublished = 2008, ISBN = 1569319014, Cover = "~/Covers/onepiece1.jpg", Description = "A new shonen sensation in Japan, this series features Monkey D. Luffy, whose main ambition is to become a pirate. Eating the Gum-Gum Fruit gives him strange powers but also invokes the fruit's curse: anybody who consumes it can never learn to swim. Nevertheless, Monkey and his crewmate Roronoa Zoro, master of the three-sword fighting style, sail the Seven Seas of swashbuckling adventure in search of the elusive treasure 'One Piece.'" };
            Book b7 = new Book() { BookId = 7, Title = "Fairy Tail, Vol. 1", Category = c4, Author = a9, Price = 9.5M, Language = "English", YearPublished = 2012, ISBN = 1612622763, Cover = "~/Covers/fairytail1.jpg", Description = "THE WICKED SIDE OF WIZARDRY Cute girl wizard Lucy wants to join the Fairy Tail, a club for the most powerful wizards. But instead, her ambitions land her in the clutches of a gang of unsavory pirates le by a devious magician. Her only hope is Natsu, a strange boy she happens to meet on her travels. Natsu's not your typical hero - he gets motion sickness, eats like a pig, and his best friend is a talking cat. With friends like this, is Lucy better off with her enemies?" };
            Book b8 = new Book() { BookId = 8, Title = "Black Jack, Vol. 2", Category = c4, Author = a10, Price = 7.5M, Language = "English", YearPublished = 2009, ISBN = 1934287288, Cover = "~/Covers/blackjack2.jpg", Description = "Black Jack is a mysterious and charismatic young genius surgeon who travels the world performing amazing and impossible medical feats. Though a trained physician, he refuses to accept a medical license due to his hatred and mistrust of the medical community's hypocrisy and corruption. Black Jack is recognized as Osamu Tezuka's third most famous series, after Astro Boy and Kimba, the White Lion." };
            Book b9 = new Book() { BookId = 9, Title = "Astro Boy, Omnibus Volume 1", Category = c4, Author = a10, Price = 20, Language = "English", YearPublished = 2015, ISBN = 1616558601, Cover = "~/Covers/astroboyomn1.jpg", Description = "Can a robot have a soul? Built by a brilliant scientist to replace his lost son, but with powers beyond imagination, Astro Boy fights for the oppressed and helpless, whether they be human, alien, or robot. Exciting, whimsical, and touching, Astro Boy brings back the classic era of comics and animation, featuring tales that readers young and old will enjoy." };
            Book b10 = new Book() { BookId = 10, Title = "Dororo", Category = c4, Author = a10, Price = 15, Language = "English", YearPublished = 2016, ISBN = 1935654322, Cover = "~/Covers/dororo.jpg", Description = "Previously published in three installments, the entire run of comic master Osamu Tezuka's enduring classic is herewith available in one volume at a new affordable price. The lauded adventures of a young swordsman and his rogue sidekick that also inspired the cult video game Blood Will Tell have never been as accessible." };
            Book b11 = new Book() { BookId = 11, Title = "A Game of Thrones", Category = c1, Author = a5, Price = 11.7M, Language = "English", YearPublished = 2009, ISBN = 0553573403, Cover = "~/Covers/GameOfThrones.jpg", Description = "Long ago, in a time forgotten, a preternatural event threw the seasons out of balance. In a land where summers can last decades and winters a lifetime, trouble is brewing. The cold is returning, and in the frozen wastes to the north of Winterfell, sinister forces are massing beyond the kingdom's protective Wall." };
            Book b12 = new Book() { BookId = 12, Title = "Wizard's First Rule", Category = c1, Author = a22, Price = 12.1M, Language = "English", YearPublished = 2004, ISBN = 0812548051, Cover = "~/Covers/WizardsFirstRule.jpg", Description = "Wizard's First Rule marks the debut of a new fantasy writer. Truly epic in scope and filled with burning intensity, it is the story of Richard Cypher, a modest woodsman in a world achingly beautiful, alive with the joys of nature: a world the reader comes to love as fiercely as do Richard and those around him. Though a mere woodsman, he is the one destined to battle the ultimate adversary - Darken Rahl, an evil mage who bids to destroy all that Richard holds good and beautiful, dooming him and the rest of the people of Westland to a living Hell of subjugation and degradation." };
            Book b13 = new Book() { BookId = 13, Title = "The Tower of the Swallow", Category = c1, Author = a23, Price = 11.3M, Language = "English", YearPublished = 2017, ISBN = 1473211573, Cover = "~/Covers/TheTowerOfTheSwallow.jpg", Description = "The world has fallen into war. Ciri, the child of prophecy, has vanished. Hunted by friends and foes alike, she has taken on the guise of a petty bandit and lives free for the first time in her life.But the net around her is closing.Geralt,the Witcher,has assembled a group of allies determined to rescue her.Both sides of the war have sent brutal mercenaries to hunt her down.Her crimes have made her famous." };
            Book b14 = new Book() { BookId = 14, Title = "The Lady of the Lake", Category = c1, Author = a23, Price = 11.3M, Language = "English", YearPublished = 2018, ISBN = 1473211603, Cover = "~/Covers/LadyOfTheLake.jpg", Description = "After walking through a portal in the Tower of the Swallow, thus narrowly escaping death, the Witcher girl, Ciri, finds herself in a completely different world... a world of the Elves. She is trapped with no way out. Time does not seem to exist and there are no obvious borders or portals to cross back into her home world." };
            Book b15 = new Book() { BookId = 15, Title = "The Legend of Drizzt 001 : Homeland", Category = c1, Author = a7, Price = 8.3M, Language = "English", YearPublished = 2005, ISBN = 0786939532, Cover = "~/Covers/Drizzt001.jpg", Description = "Drow ranger Drizzt Do'Urden, first introduced in The Icewind Dale Trilogy, quickly became one of the fantasy genre's standout characters. But Homeland first reveals the startling tale of how this one lone drow walked out of the shadowy depths of the Underdark, leaving behind a society of evil and a family who want him dead. It is here that the story of this amazing dark elf truly began." };
            Book b16 = new Book() { BookId = 16, Title = "The Legend of Drizzt 002 : Exile", Category = c1, Author = a7, Price = 8.3M, Language = "English", YearPublished = 2006, ISBN = 1473211603, Cover = "~/Covers/Drizzt002.jpg", Description = "As I became a creature of the empty tunnels, survival became easier and more difficult all at once. I gained in the physical skills and experience necessary to live on. I could defeat almost anything that wandered into my chosen domain. It did not take me long, however, to discover one nemesis that I could neither defeat nor flee. It followed me wherever I went-indeed, the farther I ran, the more it closed in around me. My enemy was solitude, the interminable, incessant silence of hushed corridors.-Drizzt Do'Urden" };
            Book b17 = new Book() { BookId = 17, Title = "The Legend of Drizzt 003 : Sojourn", Category = c1, Author = a7, Price = 8.3M, Language = "English", YearPublished = 2006, ISBN = 1473211603, Cover = "~/Covers/Drizzt003.jpg", Description = "Now in paperback, the third installment in the classic tales of the Legend of Drizzt. When a lone drow emerges from the Underdark into the blinding light of day, the Forgotten Realms world will be changed forever." };
            Book b18 = new Book() { BookId = 18, Title = "Do Androids Dream Of Electric Sheep?", Category = c2, Author = a24, Price = 4.9M, Language = "English", YearPublished = 2017, ISBN = 0575094184, Cover = "~/Covers/DoAndroidsDreamOfElectricSheep.jpg", Description = "World War Terminus had left the Earth devastated. Through its ruins, bounty hunter Rick Deckard stalked, in search of the renegade replicants who were his prey. When he wasn't 'retiring' them with his laser weapon,he dreamed of owning a live animal - the ultimate status symbol in a world all but bereft of animal life.Then Rick got his chance: the assignment to kill six Nexus-6 targets, for a huge reward." };
            Book b19 = new Book() { BookId = 19, Title = "I, Robot", Category = c2, Author = a2, Price = 16.7M, Language = "English", YearPublished = 2013, ISBN = 0007491514, Cover = "~/Covers/IRobot.jpg", Description = "Voyager Classics - timeless masterworks of science fiction and fantasy.A beautiful clothbound edition of I,Robot,the classic collection of robot stories from the master of the genre.In these stories Isaac Asimov creates the Three Laws of Robotics and ushers in the Robot Age." };
            Book b20 = new Book() { BookId = 20, Title = "The Caves of Steel (The Robot Series Book 1)", Category = c2, Author = a2, Price = 6.9M, Language = "English", YearPublished = 1993, ISBN = 0553293400, Cover = "~/Covers/CavesOfSteel.jpg", Description = "A millennium into the future two advancements have altered the course of human history: the colonization of the galaxy and the creation of the positronic brain. Isaac Asimov's 'Robot' novels chronicle the unlikely partnership between a New York City detective and a humanoid robot who must learn to work together." };
            Book b21 = new Book() { BookId = 21, Title = "The Naked Sun (The Robot Series Book 2)", Category = c2, Author = a2, Price = 8, Language = "English", YearPublished = 1991, ISBN = 0553293397, Cover = "~/Covers/nakedsun.jpg", Description = "A millennium into the future, two advancements have altered the course of human history: the colonization of the Galaxy and the creation of the positronic brain.On the beautiful Outer World planet of Solaria, a handful of human colonists lead a hermit-like existence, their every need attended to by their faithful robot servants.To this strange and provocative planet comes Detective Elijah Baley, sent from the streets of New York with his positronic partner, the robot R. Daneel Olivaw, to solve an incredible murder that has rocked Solaria to its foundations." };
            Book b22 = new Book() { BookId = 22, Title = "The Robots of Dawn (The Robot Series Book 3)", Category = c2, Author = a2, Price = 8.6M, Language = "English", YearPublished = 1994, ISBN = 0553299492, Cover = "~/Covers/robotsofdawn.jpg", Description = "A puzzling case of roboticide sends New York Detective Elijah Baley on an intense search for a murderer. Armed with his own instincts, his quirky logic, and the immutable Three Laws of Robotics, Baley is determined to solve the case. But can anything prepare a simple Earthman for the psychological complexities of a world where a beautiful woman can easily have fallen in love with an all-too-human robot...?" };
            Book b23 = new Book() { BookId = 23, Title = "Dune", Category = c2, Author = a25, Price = 10.8M, Language = "English", YearPublished = 2011, ISBN = 0441172717, Cover = "~/Covers/dune.jpg", Description = "In 1965, after being rejected by more than a dozen publishing houses, a book called 'Dune' was brought out by the Chilton Book Company. Its respected author, journalist Frank Herbert, had written 'Dune' with nothing more in mind than to entertain his readers with the telling of a particularly complex story, one which had occupied his thoughts for more than six years. No one - not Herbert, not Chilton, not the science fiction community at the time - had any idea that 'Dune' would be adopted and read by successive generations with a fervor bordering on cult worship. Or that it would prove to be merely the first of what have now become five international bestsellers about a desert world of the future - the planet Arrakis, called Dune." };
            Book b24 = new Book() { BookId = 24, Title = "The Count of Monte Cristo", Category = c3, Author = a4, Price = 5.6M, Language = "English", YearPublished = 1998, ISBN = 1853267333, Cover = "~/Covers/countofmontecristo.jpg", Description = "The story of Edmund Dantes, self-styled Count of Monte Cristo, is told with consummate skill. The victim of a miscarriage of justice, Dantes is fired by a desire for retribution and empowered by a stroke of providence. In his campaign of vengeance, he becomes an anonymous agent of fate." };
            Book b25 = new Book() { BookId = 25, Title = "Crime and Punishment", Category = c3, Author = a6, Price = 4, Language = "English", YearPublished = 2000, ISBN = 1840224304, Cover = "~/Covers/crimeandpunishment.jpg", Description = "Crime and Punishment is one of the greatest and most readable novels ever written. From the beginning we are locked into the frenzied consciousness of Raskolnikov who, against his better instincts, is inexorably drawn to commit a brutal double murder." };
            Book b26 = new Book() { BookId = 26, Title = "Sapiens : A Brief History of Humankind", Category = c5, Author = a26, Price = 12.9M, Language = "English", YearPublished = 2016, ISBN = 0099590085, Cover = "~/Covers/sapiens.jpg", Description = "What makes us brilliant? What makes us deadly? What makes us Sapiens? This bestselling history challenges everything we know about being human.Earth is 4.5 billion years old.In just a fraction of that time,one species among countless others has conquered it: us.In this bold and provocative book, Yuval Noah Harari explores who we are, how we got here and where we're going." };
            Book b27 = new Book() { BookId = 27, Title = "Homo Deus : A Brief History of Tomorrow", Category = c5, Author = a26, Price = 12.8M, Language = "English", YearPublished = 2017, ISBN = 1784703931, Cover = "~/Covers/homoDeus.jpg", Description = "Sapiens shows us where we came from. Homo Deusshows us where we're going.Yuval Noah Harari envisions a near future in which we face a new set of challenges.Homo Deus explores the projects,dreams and nightmares that will shape the twenty - first century and beyond - from overcoming death to creating artificial life.It asks the fundamental questions: how can we protect this fragile world from our own destructive power? And what does our future hold ?" };
            Book b28 = new Book() { BookId = 28, Title = "A Brief History Of Time : From Big Bang To Black Holes", Category = c5, Author = a27, Price = 10.1M, Language = "English", YearPublished = 2018, ISBN = 0553176986, Cover = "~/Covers/briefhistoryoftime.jpg", Description = "Was there a beginning of time? Could time run backwards? Is the universe infinite or does it have boundaries? These are just some of the questions considered in an internationally acclaimed masterpiece by one of the world's greatest thinkers. It begins by reviewing the great theories of the cosmos from Newton to Einstein, before delving into the secrets which still lie at the heart of space and time, from the Big Bang to black holes, via spiral galaxies and strong theory." };
            Book b29 = new Book() { BookId = 29, Title = "Getting Things Done : The art of stress-free productivity", Category = c6, Author = a28, Price = 15, Language = "English", YearPublished = 2015, ISBN = 0143573195, Cover = "~/Covers/GTD.jpg", Description = "David Allen's Getting Things Done was hailed as 'the definitive business self-help book of the decade' (Time) when it was first published almost fifteen years ago, and ' GTD' has since become shorthand for an entire culture of personal organization that offers to change the way people work and live. Now the veteran coach and management consultant has rewritten the book from start to finish, tweaking his classic text with new perspectives on today's workplace and incorporating new data that validates his timeless admonition that 'your hear is for having ideas - not for holding them!'" };
            Book b30 = new Book() { BookId = 30, Title = "The Little Book of Ikigai", Category = c6, Author = a29, Price = 16.5M, Language = "English", YearPublished = 2018, ISBN = 1786489031, Cover = "~/Covers/ikigai.jpg", Description = "Find out how to live a long and happy life thanks to the ikigai miracle, a Japanese philosophy that helps you find fulfilment, joy and mindfulness in everything you do." };
            Book b31 = new Book() { BookId = 31, Title = "12 Rules for Life", Category = c6, Author = a30, Price = 11, Language = "English", YearPublished = 2019, ISBN = 0141988517, Cover = "~/Covers/rulesoflife.jpg", Description = "Drawing on his own work as a clinical psychologist and on lessons from humanity's oldest myths and stories, Peterson offers twelve profound and realistic principles to live by. After all, as he reminds us, we each have a vital role to play in the unfolding destiny of the world." };
            Book b32 = new Book() { BookId = 32, Title = "Western Philosophy: An Anthology", Category = c7, Author = a31, Price = 31.3M, Language = "English", YearPublished = 2007, ISBN = 1405124784, Cover = "~/Covers/westernphilosophy.jpg", Description = "Western Philosophy: An Anthology provides the most comprehensive and authoritative survey of the Western philosophical tradition from ancient Greece to the leading philosophers of today." };
            Book b33 = new Book() { BookId = 33, Title = "The Art of War", Category = c7, Author = a32, Price = 3.9M, Language = "English", YearPublished = 2011, ISBN = 0007420129, Cover = "~/Covers/artofwar.jpg", Description = "Written in the 6th century BC,Sun Tzu's The Art of War is a Chinese military treatise that is still revered today as the ultimate commentary on war and military strategy. Focussing on the principle that one can outsmart your foe mentally by thinking very carefully about strategy before resorting to physical battle, this philosophy continues to be applied to the corporate and business world." };
            Book b34 = new Book() { BookId = 34, Title = "Music Theory in Practice, Grade 1", Category = c8, Author = a33, Price = 7.3M, Language = "English", YearPublished = 2008, ISBN = 1860969429, Cover = "~/Covers/musictheory1.jpg", Description = "The Music Theory in Practice series has helped more than one million musicians worldwide to learn about the notation and theory of music. Now fully revised, this workbook remains the best way to prepare for ABRSM's Grade 1 Theory of Music Exam." };
            Book b35 = new Book() { BookId = 35, Title = "Music Theory in Practice, Grade 2", Category = c8, Author = a33, Price = 7.9M, Language = "English", YearPublished = 2008, ISBN = 1860969437, Cover = "~/Covers/musictheory2.jpg", Description = "The Music Theory in Practice series has helped more than one million musicians worldwide to learn about the notation and theory of music. Now fully revised, this workbook remains the best way to prepare for ABRSM's Grade 2 Theory of Music Exam." };
            Book b36 = new Book() { BookId = 36, Title = "Music Theory in Practice, Grade 3", Category = c8, Author = a33, Price = 8.5M, Language = "English", YearPublished = 2008, ISBN = 1860969445, Cover = "~/Covers/musictheory3.jpg", Description = "The Music Theory in Practice series has helped more than one million musicians worldwide to learn about the notation and theory of music. Now fully revised, this workbook remains the best way to prepare for ABRSM's Grade 3 Theory of Music Exam." };
            Book b37 = new Book() { BookId = 37, Title = "Music Theory in Practice, Grade 4", Category = c8, Author = a33, Price = 10.2M, Language = "English", YearPublished = 2008, ISBN = 1860969453, Cover = "~/Covers/musictheory4.jpg", Description = "The Music Theory in Practice series has helped more than one million musicians worldwide to learn about the notation and theory of music. Now fully revised, this workbook remains the best way to prepare for ABRSM's Grade 4 Theory of Music Exam." };
            Book b38 = new Book() { BookId = 38, Title = "Music Theory in Practice, Grade 5", Category = c8, Author = a33, Price = 9.7M, Language = "English", YearPublished = 2008, ISBN = 1860969461, Cover = "~/Covers/musictheory5.jpg", Description = "The Music Theory in Practice series has helped more than one million musicians worldwide to learn about the notation and theory of music. Now fully revised, this workbook remains the best way to prepare for ABRSM's Grade 5 Theory of Music Exam." };
            Book b39 = new Book() { BookId = 39, Title = "Art : The Definitive Visual Guide", Category = c9, Author = a34, Price = 57.5M, Language = "English", YearPublished = 2008, ISBN = 0241257107, Cover = "~/Covers/artguide.jpg", Description = "Discover the history of art movements from classical Greek art to the Italian Renaissance, the Pre-Raphaelites, and the masters of Impressionism with a brand new edition of this classic bestseller.Truly comprehensive in scope,Art shows you masterpieces from over 700 artists,including Leonardo da Vinci,Picasso,and Van Gogh.An invaluable reference book for any art lover, it showcases the works; everything from Italian baroque painting and African art to contemporary art history." };
            Book b40 = new Book() { BookId = 40, Title = "The Art of Howl's Moving Castle", Category = c9, Author = a35, Price = 21.4M, Language = "English", YearPublished = 2008, ISBN = 1421500493, Cover = "~/Covers/arthowlcastle.jpg", Description = "A hardback, prestige format book with a generous collection of concept sketches, fully rendered character and background drawings, paintings and cell images. Along with the stunning visuals, the book also presents interviews and comments with the production staff, including key points from the director." };
            Book b41 = new Book() { BookId = 41, Title = "The Art of Spirited Away", Category = c9, Author = a35, Price = 18, Language = "English", YearPublished = 2008, ISBN = 1569317771, Cover = "~/Covers/artspiritedaway.jpg", Description = "The Art of Spirited Awaycollects colour illustrations of Spirited Awayfor the first time in an English edition. This book includes paintings and designs from the Academy Award winning animated film directed by Hayao Miyazaki. Features commentary, colour stills, sketches, storyboards, and illustrations used to envision the rich fantasy world of the film. Also includes a complete English-language script." };
            Book b42 = new Book() { BookId = 42, Title = "Nausicaa of the Valley of the Wind Box Set", Category = c4, Author = a35, Price = 74.4M, Language = "English", YearPublished = 2012, ISBN = 1421550644, Cover = "~/Covers/nausicaa.jpg", Description = "Nausicaa of the Valley of the Wind is an epic fantasy tale written and illustrated by legendary Studio Ghibli director Hayao Miyazaki, creator of My Neighbor Totoro, Spirited Away and Howl's Moving Castle. A modern masterpiece, the entire series is now available in this deluxe box set containing two hardcover volumes with interior colour pages and a bonus poster." };
            Book b43 = new Book() { BookId = 43, Title = "Atomic Habits", Category = c6, Author = a11, Price = 19, Language = "English", YearPublished = 2018, ISBN = 1935654322, Cover = "~/Covers/AtomicHabits.jpg", Description = "People think when you want to change your life, you need to think big. But world-renowned habits expert James Clear has discovered another way. He knows that real change comes from the compound effect of hundreds of small decisions - doing two push-ups a day, waking up five minutes early, or holding a single short phone call." };
            Book b44 = new Book() { BookId = 44, Title = "Meditations", Category = c7, Author = a12, Price = 5, Language = "English", YearPublished = 2019, ISBN = 0753820161, Cover = "~/Covers/Meditations.jpg", Description = "Few ancient works have been as influential as the MEDITATIONS of Marcus Aurelius. A series of spiritual exercises filled with wisdom, practical guidance, and profound understanding of human behaviour, it remains one of the greatest works of spiritual and ethical reflection ever written. Marcuss insights and advice - on everything from living in the world to coping with adversity and interacting with others - have made the MEDITATIONS required reading for statesmen and philosophers alike, while generations of ordinary readers have responded to the straightforward intimacy of his style." };
            Book b45 = new Book() { BookId = 45, Title = "Normal People", Category = c3, Author = a13, Price = 10, Language = "English", YearPublished = 2016, ISBN = 0571334652, Cover = "~/Covers/NormalPeople.jpg", Description = "Connell and Marianne grow up in the same small town in the west of Ireland, but the similarities end there. In school, Connell is popular and well-liked, while Marianne is a loner. But when the two strike up a conversation - awkward but electrifying - something life-changing begins.Normal People is a story of mutual fascination, friendship and love. It takes us from that first conversation to the years beyond, in the company of two people who try to stay apart but find they cant." };
            Book b46 = new Book() { BookId = 46, Title = "Me:Elton John", Category = c8, Author = a14, Price = 19, Language = "English", YearPublished = 2019, ISBN = 1509853316, Cover = "~/Covers/Me.jpg", Description = "In his first and only official autobiography, music icon Elton John reveals the truth about his extraordinary life, which is also the subject of the smash-hit film Rocketman. The result is Me - the joyously funny, honest and moving story of the most enduringly successful singer/songwriter of all time." };
            Book b47 = new Book() { BookId = 47, Title = "His Dark Materials: Lyras Oxford", Category = c1, Author = a15, Price = 8, Language = "English", YearPublished = 2017, ISBN = 0399555455, Cover = "~/Covers/HisDarkMaterials.jpg", Description = "HIS DARK MATERIALS IS SOON TO BE AN HBO ORIGINAL SERIES STARRING DAFNE KEEN, RUTH WILSON, JAMES McAVOY, AND LIN-MANUEL MIRANDA! This exciting companion to His Dark Materials tells a not-to-be-missed story about Lyra and her world. When a witchs daemon crashes onto the roof of Jordan College, Lyra and her daemon, Pan, are eager to help. But as this unlikely trio scours the winding streets of Oxford in search of a famed alchemist, their journey takes a deadly turn... This volume also includes a fold-out map of Oxford and fascinating extra glimpses of our favorite characters. Dont miss Philip Pullmans epic new trilogy set in the world of His Dark Materials!" };
            Book b48 = new Book() { BookId = 48, Title = "Lie With Me", Category = c3, Author = a16, Price = 9, Language = "English", YearPublished = 2019, ISBN = 0241987091, Cover = "~/Covers/LieWithMe.jpg", Description = "Just outside a hotel in Bordeaux, Philippe, a famous writer, chances upon a young man who bears a striking resemblance to his first love. What follows is a look back to Philippes teenage years, to a winter morning in 1984, a small French high school, and a carefully timed encounter between two seventeen-year-olds. Its the start of a secret, intensely passionate, world-altering love affair between Philippe and his classmate, Thomas." };
            Book b49 = new Book() { BookId = 49, Title = "An Orchestra of Minorities", Category = c3, Author = a17, Price = 10, Language = "English", YearPublished = 2019, ISBN = 0349143188, Cover = "~/Covers/AnOrchestra.jpg", Description = "A young farmer named Chinonso prevents a woman from falling to her death. Bonded by this strange night on the bridge, he and Ndali fall in love, but it is a mismatch according to her family who reject him because of his lowly status. Is it love or madness that makes Chinonso think he can change his destiny?" };
            Book b50 = new Book() { BookId = 50, Title = "Twas The Nightshift Before Christmas", Category = c3, Author = a18, Price = 9, Language = "English", YearPublished = 2019, ISBN = 1529018587, Cover = "~/Covers/TwasTheNightShift.jpg", Description = "Twas the Nightshift Before Christmas is a love letter to all those who spend their festive season on the front line, removing babies and baubles from the various places they get stuck, at the most wonderful time of the year." };
            Book b51 = new Book() { BookId = 51, Title = "Eight White Nights", Category = c3, Author = a19, Price = 11, Language = "English", YearPublished = 2011, ISBN = 1848876211, Cover = "~/Covers/EightWhiteNights.jpg", Description = "A man in his late twenties goes to a large Christmas party in Manhattan where a woman introduces herself with three words: I am Clara.Over the following seven days, they meet every evening in the snowy city. Overwhelmed yet cautious, he treads softly and wont hazard a move. But as they move closer together, this amorous dance builds towards a New Years Eve charged with magic, the promise of renewal and love." };
            Book b52 = new Book() { BookId = 52, Title = "The Storm Dog", Category = c1, Author = a20, Price = 7, Language = "English", YearPublished = 2019, ISBN = 1788950453, Cover = "~/Covers/StormDog.jpg", Description = "When Tilly travels by herself on the train for the first time, she ends up falling asleep, only to wake up and discover that shes travelled all the way back to World War II, where shes being evacuated to Wales with her two younger brothers. Stern Mr Edwards offers to give them a home on his remote farm, and there she meets a very special sheepdog..." };
            Book b53 = new Book() { BookId = 53, Title = "The Body", Category = c5, Author = a21, Price = 22, Language = "English", YearPublished = 2019, ISBN = 085752240, Cover = "~/Covers/TheBody.jpg", Description = "Bill Bryson sets off to explore the human body, how it functions and its remarkable ability to heal itself. Full of extraordinary facts and astonishing stories The Body: A Guide for Occupants is a brilliant, often very funny attempt to understand the miracle of our physical and neurological make up." };
            context.Books.AddOrUpdate(x => x.Title, b1, b2, b3, b4, b5, b6, b7, b8, b9, b10, b11, b12, b13, b14, b15, b16, b17, b18, b19, b20, b21, b22, b23, b24, b25, b26, b27, b28, b29, b30, b31, b32, b33, b34, b35, b36, b37, b38, b39, b40, b41, b42, b43, b44, b45, b46, b47, b48, b49, b50, b51, b52, b53);
            context.SaveChanges();
        }
    }
}
